### ISSUE TITLE
LGPL License present in the core kubernetes repository

### ISSUE THREAD

**Issue by kujenga** [kubernetes/steering#23] opened 2018-01-25 15:09 UTC
@kujenga commented on [Mon Jan 08 2018](https://github.com/kubernetes/client-go/issues/357)

There is an LGPL license for code that is vendored in client-go: https://github.com/kubernetes/client-go/blob/master/vendor/github.com/juju/ratelimit/LICENSE

It appears that this is inherited from the main Kubernetes repository: https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/juju/ratelimit/LICENSE

Does this not "infect" use of the code in this repository in some way? What compatibility is there with the Apache 2.0 license that this repository bears?

Edit: Apache lists incompatible licenses: http://www.apache.org/legal/resolved.html#category-x

---

@sttts commented on [Mon Jan 22 2018](https://github.com/kubernetes/client-go/issues/357#issuecomment-359389937)

Can you move this discussion to https://github.com/kubernetes/steering/issues/21 ?

---

@denismakogon commented on [Wed Jan 24 2018](https://github.com/kubernetes/client-go/issues/357#issuecomment-360249142)

Okay, so, do we already know when the client would get rid of juju/ratelimit ?

---

@sttts commented on [Wed Jan 24 2018](https://github.com/kubernetes/client-go/issues/357#issuecomment-360254271)

@denismakogon https://github.com/kubernetes/kubernetes/pull/38320

---

@sttts commented on [Wed Jan 24 2018](https://github.com/kubernetes/client-go/issues/357#issuecomment-360254507)

@denismakogon some hours after the upper PR is merged, you see it here.

---

@denismakogon commented on [Wed Jan 24 2018](https://github.com/kubernetes/client-go/issues/357#issuecomment-360255382)

@sttts thanks!

**Comment by kujenga** [comment] 2018-01-25 15:10
This issue was moved here with ZenHub per the request of @sttts

**Comment by sttts** [comment] 2018-01-25 16:41
This is probably a duplicate of https://github.com/kubernetes/steering/issues/21. Client-go is an artifact of of k8s.io/kubernetes (which is the topic of https://github.com/kubernetes/steering/issues/21).

**Comment by liggitt** [comment] 2018-01-26 04:05
/close
in favor of #21

**Closed by liggitt** 2018-01-26 04:05 UTC
