### ISSUE TITLE
Document rule around CoCC and SC

### ISSUE THREAD

**Issue by jberkus** [kubernetes/steering#271] opened 2023-08-15 00:10 UTC
### Problem Statement

It has been de-facto Steering Committee policy for the last 2+ years that nobody can be on both the CoCC and the SC at the same time.  However, this isn't documented in either the SC or the CoCC election materials, rules, or bylaws.  As a result, this month we have someone who is running for both offices.  Because, why shouldn't they?

### Proposed Solution

Both the CoCC and the SC candidate materials should clearly spell out that you can't be on both bodies at once.

### Cost

N/A

### Open Questions

Can someone run for both, and only accept one?  If so, under what circumstances?

### Next Steps
- [ ] Steering to write final CoCC/SC conflict policy
- [ ] Steering to direct CoCC and Elections subproj to add that to documentation

**Comment by justaugustus** [comment] 2023-08-15 17:05
Closing as duplicate of https://github.com/kubernetes/steering/issues/221.
/close

**Closed** 2023-08-15 17:10 UTC
